#            ___  _ _   _ _             _        _   _ _   _ _ _ _             
#           / _ \| | | (_| |           | |      | | | | | (_| (_| |            
#          / /_\ | | |_ _| |_ _   _  __| | ___  | | | | |_ _| |_| |_ _   _     
#          |  _  | | __| | __| | | |/ _` |/ _ \ | | | | __| | | | __| | | |    
#          | | | | | |_| | |_| |_| | (_| |  __/ | |_| | |_| | | | |_| |_| |    
#          \_| |_|_|\__|_|\__|\__,_|\__,_|\___|  \___/ \__|_|_|_|\__|\__, |    
#                                                                     __/ |    
#                                                                    |___/     
#                                  _             _   __                        
#                                 | |           | | / /                        
#                                 | |__  _   _  | |/ /  __ _ _ __  _ __   __ _ 
#                                 | '_ \| | | | |    \ / _` | '_ \| '_ \ / _` |
#                                 | |_) | |_| | | |\  | (_| | |_) | |_) | (_| |
#                                 |_.__/ \__, | \_| \_/\__,_| .__/| .__/ \__,_|
#                                         __/ |             | |   | |          
#                                        |___/              |_|   |_|          
#
# A group of utilities made for the Altitude Minecraft server.

