version: 6.9 hehe

name: AlttdUtility
description: A group of utilities made for Altitude

author: Kap

main: com.darko.main.Main
api-version: 1.15
commands:
  chair:
    permission: utility.chair
  hat:
    permission: utility.hat
  servermsg:
    permission: utility.servermsg
  cooldown:
    permission: utility.cooldown
  online:
    permission: utility.online
  autofix:
    permission: utility.autofix
  utilityconfigreload:
    permission: utility.configreload
  list:
      permission: utility.list