version: 6.9 hehe

name: AlttdUtility
description: A group of utilities made for Altitude

author: Kap

main: com.darko.main.Main
api-version: 1.15
commands:

  chair:
  hat:
  servermsg:
  cooldown:
  online:
  autofix: