version: 6.9 hehe

name: AlttdUtility
description: A group of utilities made for Altitude

author: Darko

main: com.darko.main.Main
api-version: 1.13
commands:

  chair:
  hat:
  servermsg:
  cooldown:
  kick:
  warn:
  tempmute:
  tempban:
  ban: