#            ___  _ _   _ _             _        _   _ _   _ _ _ _
#           / _ \| | | (_| |           | |      | | | | | (_| (_| |
#          / /_\ | | |_ _| |_ _   _  __| | ___  | | | | |_ _| |_| |_ _   _
#          |  _  | | __| | __| | | |/ _` |/ _ \ | | | | __| | | | __| | | |
#          | | | | | |_| | |_| |_| | (_| |  __/ | |_| | |_| | | | |_| |_| |
#          \_| |_|_|\__|_|\__|\__,_|\__,_|\___|  \___/ \__|_|_|_|\__|\__, |
#                                                                     __/ |
#                                                                    |___/
#                                  _             _   __
#                                 | |           | | / /
#                                 | |__  _   _  | |/ /  __ _ _ __  _ __   __ _
#                                 | '_ \| | | | |    \ / _` | '_ \| '_ \ / _` |
#                                 | |_) | |_| | | |\  | (_| | |_) | |_) | (_| |
#                                 |_.__/ \__, | \_| \_/\__,_| .__/| .__/ \__,_|
#                                         __/ |             | |   | |
#                                        |___/              |_|   |_|
#
# A group of utilities made for the Altitude Minecraft server.
# Why am I even writing this, Teri you're probably the only one who's gonna read this.
# Maybe some other admin too. But that would probably mean something fucked up since the config is set it and forget it type deal.
# Anyways, bring back sugar cane :)

