version: 6.9 hehe
name: AlttdUtility
description: A group of utilities made for Altitude
author: Daki
main: com.darko.main.AlttdUtility
api-version: 1.16
loadbefore: [WorldGuard]
softdepend: [CMI]
commands:
  hat:
    permission: utility.hat
  servermsg:
    permission: utility.servermsg
  cooldown:
    permission: utility.cooldown
  autofix:
    permission: utility.autofix
  kickfrombungee:
    permission: utility.kickfrombungee
  alttdutilityreload:
    permission: utility.alttdutilityreload
  list:
    permission: utility.list
  setprefix:
    permission: utility.setprefix
  removeprefix:
    permission: utility.removeprefix
  prefixhistory:
    premission: utility.prefixhistory
  blockitempickup:
    permission: utility.blockitempickup
  crash:
    permission: utility.crash
  searchlogs:
    permission: utility.searchlogs
  invisitemframes:
    permission: utility.invisitemframes
  rebootwhitelist:
    permission: utility.rebootwhitelist
  sit:
    permission: utility.sit
  togglegc:
    permission: utility.togglegc
  commandonjoin:
    permission: utility.commandonjoin
  ccm:
    permission: utility.ccm
  freezemail:
    permission: utility.freezemail
  nick:
    permission: utility.nick
  godmode:
    permission: utility.godmode
  petgodmode:
    permission: utility.petgodmode
  claimpatrol:
    permission: utility.claimpatrol
  togglescruff:
    permission: utility.togglescruff