version: 6.9 hehe
name: AlttdUtility
description: A group of utilities made for Altitude
author: Daki
main: com.darko.main.AlttdUtility
api-version: 1.18
softdepend: [GriefPrevention, WorldGuard, LuckPerms, MyPet, CrazyCrates, mcMMO, FarmLimiter, PvPManager, CMI, VillagerShopUI, ProtocolLib]
commands:
  hat:
    permission: utility.hat
  servermsg:
    permission: utility.servermsg
  cooldown:
    permission: utility.cooldown
  autofix:
    permission: utility.autofix
  kickfrombungee:
    permission: utility.kickfrombungee
  alttdutilityreload:
    permission: utility.alttdutilityreload
  list:
    permission: utility.list
  setprefix:
    permission: utility.setprefix
  removeprefix:
    permission: utility.removeprefix
  prefixhistory:
    premission: utility.prefixhistory
  blockitempickup:
    permission: utility.blockitempickup
  crash:
    permission: utility.crash
  searchlogs:
    permission: utility.searchlogs
  invisitemframes:
    permission: utility.invisitemframes
  rebootwhitelist:
    permission: utility.rebootwhitelist
  sit:
    permission: utility.sit
#  togglegc:
#    permission: utility.togglegc
  commandonjoin:
    permission: utility.commandonjoin
  ccm:
    permission: utility.ccm
  freezemail:
    permission: utility.freezemail
  nick:
    permission: utility.nick
  godmode:
    permission: utility.godmode
  petgodmode:
    permission: utility.petgodmode
  claimpatrol:
    permission: utility.claimpatrol
  togglescruff:
    permission: utility.togglescruff
  trapped:
    permission: utility.trapped
  tppunch:
    permission: utility.tppunch
  commandusage:
    permission: utility.commandusage
  saveitem:
    permission: utility.saveitem
  viewsaveditems:
    permission: utility.viewsaveditems
  magnet:
    permission: utility.magnet