version: 6.9 hehe
name: AlttdUtility
description: A group of utilities made for Altitude
author: Daki
main: com.darko.main.Main
api-version: 1.16
commands:
  chair:
    permission: utility.chair
  hat:
    permission: utility.hat
  servermsg:
    permission: utility.servermsg
  cooldown:
    permission: utility.cooldown
  online:
    permission: utility.online
  autofix:
    permission: utility.autofix
  kickfrombungee:
    permission: utility.kickfrombungee
  utilityconfigreload:
    permission: utility.configreload
  list:
    permission: utility.list
  setprefix:
    permission: utility.setprefix
  removeprefix:
    permission: utility.removeprefix
  prefixhistory:
    premission: utility.prefixhistory
  recompresslogs:
    permission: utility.recompresslogs
  togglepickup:
    permission: utility.togglepickup